#pragma once

namespace movesense {

#define MAX_BUFFER_BYTES_LENGTH 1920*1080*3	 

enum MS_ERROR
{
    MS_SUCCESS = 0,
    MS_FAIL = -1,
    MS_TIMEOUT = -2,
	MS_NO_DEVICE = -3,
	MS_NOT_SUPPORT = -4,
};

enum MS_CHANNEL
{
	MS_CHANNEL_FORWARD = 0x01,
	MS_CHANNEL_DOWN	= 0x02,
	MS_CHANNEL_LEFT	= 0x04,
	MS_CHANNEL_BACK	= 0x08,
	MS_CHANNEL_RIGHT	= 0x10,
	MS_CHANNEL_ALL = MS_CHANNEL_FORWARD | MS_CHANNEL_DOWN | MS_CHANNEL_LEFT | MS_CHANNEL_BACK | MS_CHANNEL_RIGHT
};

}
